apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME-ing
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: APP_NAME.armyost.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: APP_NAME-svc
              port:
                number: 80
